import {test,expect} from '@playwright/test';
test('analytics uses profile colors, real counts, date filters and contained mobile charts',async({page,context})=>{
 await context.addCookies([{name:'m8-access',value:'test',domain:'localhost',path:'/'}]);
 await page.clock.setFixedTime(new Date('2026-09-28T15:00:00Z'));
 await page.route('**/api/activity',r=>r.fulfill({json:{}}));
 const base={origin:'Tarefa manual',source_key:'manual:1',priority:'normal',assigned_to:'sara@example.com',assignee_name:'Sara',created_at:'2026-09-02T12:00:00Z'};
 await page.route('**/api/tasks',r=>r.fulfill({json:{email:'sara@example.com',users:[{email:'sara@example.com',display_name:'Sara',task_color:'#ad2277'}],tasks:[{...base,id:'3',title:'Outra',status:'not_started',assigned_to:'maick@example.com',assignee_name:'Maick'},{...base,id:'1',title:'Pendente',status:'not_started'},{...base,id:'2',title:'Feita',status:'completed',completed_at:'2026-09-20T12:00:00Z'}]}}));
 await page.goto('/tarefas');await page.getByRole('button',{name:'Gráfico',exact:true}).click();
 await expect(page.locator('rect[data-responsible="sara@example.com"]')).toHaveAttribute('fill','#ad2277');
 await expect(page.locator('.analytics-metric').nth(0)).toContainText('3');
 await expect(page.locator('.analytics-metric').nth(1)).toContainText('1');
 await expect(page.getByLabel('Data inicial do gráfico')).not.toBeVisible();
 const labels=page.locator('[data-series="pending"]');
 await expect(labels.last()).toHaveText('2');
 await page.getByRole('button',{name:'Filtrar evolução por Maick',exact:true}).locator('text').last().click();
 await expect(labels.last()).toHaveText('1');
 await expect(page.locator('.analytics-cross-filter')).toContainText('Maick');
 await expect(page.locator('[data-series="closed"]')).toHaveCount(28);
 await page.getByRole('button',{name:'Limpar responsável'}).click();
 await expect(labels.last()).toHaveText('2');
 await page.locator('rect[data-responsible="sara@example.com"]').click();
 await expect(labels.last()).toHaveText('1');
 await page.getByRole('button',{name:'Filtrar evolução por Sara',exact:true}).press('Enter');
 await expect(labels.last()).toHaveText('2');
 await page.locator('.analytics-filter-panel summary').click();
 await page.getByLabel('Data inicial do gráfico').fill('2026-09-10');
 await expect(page.locator('.analytics-metric').nth(0)).toContainText('0');
 await expect(page.locator('.analytics-metric').nth(1)).toContainText('1');
 await page.setViewportSize({width:390,height:844});
 expect(await page.locator('.task-analytics').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
 await expect(page.getByLabel('Intervalo da evolução')).toBeVisible();
});
