// Campos do briefing; confirmar tipos/capitalização com a API real antes da carga.
export type FieldType = 'text' | 'bigint' | 'numeric' | 'boolean' | 'timestamptz' | 'enum_text';
export interface EntitySchema { table: string; collection: string | null; fields: readonly (readonly [string, string, FieldType])[] }
export const schemas = [
  { table: 'm8_ordens_servico', collection: null, fields: [
    ['cliente_id', 'clienteId', 'bigint'],
    ['cliente_nome', 'clienteNome', 'text'],
    ['cliente_razao_social', 'clienteRazaoSocial', 'text'],
    ['cliente_cpf_cnpj', 'clienteCpfCnpj', 'text'],
    ['data_abertura', 'dataAbertura', 'timestamptz'],
    ['data_entrega_prevista', 'dataEntregaPrevista', 'timestamptz'],
    ['data_entrega', 'dataEntrega', 'timestamptz'],
    ['emissao', 'emissao', 'timestamptz'],
    ['data_lancamento', 'dataLancamento', 'timestamptz'],
    ['data_faturamento', 'dataFaturamento', 'timestamptz'],
    ['data_atualizacao', 'dataAtualizacao', 'timestamptz'],
    ['data_garantia', 'dataGarantia', 'timestamptz'],
    ['tipo_id', 'tipoId', 'bigint'],
    ['tipo_nome', 'tipoNome', 'text'],
    ['contato', 'contato', 'text'],
    ['funcionario_id', 'funcionarioId', 'bigint'],
    ['funcionario_nome', 'funcionarioNome', 'text'],
    ['revenda_contrato_id', 'revendaContratoId', 'bigint'],
    ['revenda_contrato_nome', 'revendaContratoNome', 'text'],
    ['endereco_entrega_id', 'enderecoEntregaId', 'bigint'],
    ['endereco_entrega_nome', 'enderecoEntregaNome', 'text'],
    ['condicao_pagamento_id', 'condicaoPagamentoId', 'bigint'],
    ['condicao_pagamento_nome', 'condicaoPagamentoNome', 'text'],
    ['responsavel_tecnico_id', 'responsavelTecnicoId', 'bigint'],
    ['responsavel_tecnico_nome', 'responsavelTecnicoNome', 'text'],
    ['numero_sequencia', 'numeroSequencia', 'bigint'],
    ['situacao_id', 'situacaoId', 'bigint'],
    ['situacao_nome', 'situacaoNome', 'text'],
    ['status_lancamento_id', 'statusLancamentoId', 'bigint'],
    ['status_lancamento_nome', 'statusLancamentoNome', 'text'],
    ['status', 'status', 'text'],
    ['status_aprovacao', 'statusAprovacao', 'enum_text'],
    ['tipo_atendimento_id', 'tipoAtendimentoId', 'bigint'],
    ['tipo_atendimento_nome', 'tipoAtendimentoNome', 'text'],
    ['modalidade_atendimento_id', 'modalidadeAtendimentoId', 'bigint'],
    ['modalidade_atendimento_nome', 'modalidadeAtendimentoNome', 'text'],
    ['defeitos_apontados', 'defeitosApontados', 'text'],
    ['modelo_veiculo', 'modeloVeiculo', 'text'],
    ['placa_veiculo', 'placaVeiculo', 'text'],
    ['serie', 'serie', 'text'],
    ['numero_serie', 'numeroSerie', 'text'],
    ['equipamento', 'equipamento', 'text'],
    ['produto_equipamento_id', 'produtoEquipamentoId', 'bigint'],
    ['modelo_equipamento', 'modeloEquipamento', 'text'],
    ['documento_equipamento', 'documentoEquipamento', 'text'],
    ['tipo_documento_fiscal', 'tipoDocumentoFiscal', 'bigint'],
    ['documento_fiscal_id', 'documentoFiscalId', 'bigint'],
    ['documento_compra_id', 'documentoCompraId', 'bigint'],
    ['documento_compra_doc', 'documentoCompraDoc', 'bigint'],
    ['imposto', 'imposto', 'text'],
    ['origem_dados', 'origemDados', 'text'],
    ['projeto_id', 'projetoId', 'bigint'],
    ['projeto_nome', 'projetoNome', 'text'],
    ['empresa_id', 'empresaId', 'bigint'],
    ['empresa_nome', 'empresaNome', 'text'],
    ['empresa_grupo_nome', 'empresaGrupoNome', 'text'],
    ['total_geral', 'totalGeral', 'numeric'],
    ['ativo', 'ativo', 'boolean'],
    ['atualizado_pelo_usuario_id', 'atualizadoPeloUsuarioId', 'bigint'],
    ['observacao', 'observacao', 'text'],
  ] },
  { table: 'm8_os_produtos', collection: 'produtos', fields: [
    ['produto_id', 'produtoId', 'bigint'],
    ['produto_nome', 'produtoNome', 'text'],
    ['tipo_contrato', 'tipoContrato', 'bigint'],
    ['referencia_fabricante', 'referenciaFabricante', 'text'],
    ['multiplo_venda', 'multiploVenda', 'numeric'],
    ['codigo_similaridade', 'codigoSimilaridade', 'text'],
    ['descricao_detalhada_nfe', 'descricaoDetalhadaNfe', 'text'],
    ['destino_estoque_id', 'destinoEstoqueId', 'bigint'],
    ['destino_estoque_nome', 'destinoEstoqueNome', 'text'],
    ['unidade_id', 'unidadeId', 'bigint'],
    ['unidade_nome', 'unidadeNome', 'text'],
    ['valor_total', 'valorTotal', 'numeric'],
    ['situacao_item_id', 'situacaoItemId', 'bigint'],
    ['situacao_item_nome', 'situacaoItemNome', 'text'],
    ['quantidade', 'quantidade', 'numeric'],
    ['valor_unitario', 'valorUnitario', 'numeric'],
    ['peso_liquido', 'pesoLiquido', 'numeric'],
    ['volume_nome', 'volumeNome', 'text'],
    ['observacao_interna', 'observacaoInterna', 'text'],
    ['observacao', 'observacao', 'text'],
    ['saldo', 'saldo', 'numeric'],
    ['faturado', 'faturado', 'numeric'],
    ['operacao_fiscal_id', 'operacaoFiscalId', 'bigint'],
    ['tributacao_operacao_fiscal_id', 'tributacaoOperacaoFiscalId', 'bigint'],
    ['cst', 'cst', 'text'],
    ['quantidade_conversao', 'quantidadeConversao', 'numeric'],
    ['valor_unitario_conversao', 'valorUnitarioConversao', 'numeric'],
    ['valor_unitario_desconto', 'valorUnitarioDesconto', 'numeric'],
    ['percentual_desconto', 'percentualDesconto', 'numeric'],
    ['valor_desconto', 'valorDesconto', 'numeric'],
    ['valor_desconto_rateio', 'valorDescontoRateio', 'numeric'],
    ['fator_conversao', 'fatorConversao', 'numeric'],
    ['valor_total_conversao', 'valorTotalConversao', 'numeric'],
    ['unidade_conversao_id', 'unidadeConversaoId', 'bigint'],
    ['unidade_conversao_nome', 'unidadeConversaoNome', 'text'],
    ['base_calculo_icms_diferencial', 'baseCalculoIcmsDiferencial', 'numeric'],
    ['aliquota_icms', 'aliquotaIcms', 'numeric'],
    ['aliquota_icms_st', 'aliquotaIcmsSt', 'numeric'],
    ['percentual_reducao_icms', 'percentualReducaoIcms', 'numeric'],
    ['aliquota_mva', 'aliquotaMva', 'numeric'],
    ['aliquota_pis', 'aliquotaPis', 'numeric'],
    ['aliquota_cofins', 'aliquotaCofins', 'numeric'],
    ['aliquota_ipi', 'aliquotaIpi', 'numeric'],
    ['aliquota_funrural', 'aliquotaFunrural', 'numeric'],
    ['aliquota_icms_diferencial', 'aliquotaIcmsDiferencial', 'numeric'],
    ['valor_icms', 'valorIcms', 'numeric'],
    ['valor_icms_st', 'valorIcmsSt', 'numeric'],
    ['valor_pis', 'valorPis', 'numeric'],
    ['valor_cofins', 'valorCofins', 'numeric'],
    ['valor_ipi', 'valorIpi', 'numeric'],
    ['valor_icms_diferencial', 'valorIcmsDiferencial', 'numeric'],
    ['aprovado', 'aprovado', 'text'],
    ['codigo_pedido', 'codigoPedido', 'text'],
    ['numero_item_pedido', 'numeroItemPedido', 'bigint'],
    ['prazo_entrega', 'prazoEntrega', 'text'],
    ['percentual_comissao_tabela_preco', 'percentualComissaoTabelaPreco', 'numeric'],
    ['data_atualizacao', 'dataAtualizacao', 'timestamptz'],
    ['esta_excluido', 'estaExcluido', 'boolean'],
  ] },
  { table: 'm8_os_servicos', collection: 'servicos', fields: [
    ['servico_id', 'servicoId', 'bigint'],
    ['servico_nome', 'servicoNome', 'text'],
    ['quantidade', 'quantidade', 'numeric'],
    ['valor_unitario', 'valorUnitario', 'numeric'],
    ['valor_total', 'valorTotal', 'numeric'],
    ['data_atualizacao', 'dataAtualizacao', 'timestamptz'],
  ] },
  { table: 'm8_os_apontamentos', collection: 'apontamentos', fields: [
    ['servico_id', 'servicoId', 'bigint'],
    ['servico_nome', 'servicoNome', 'text'],
    ['funcionario_id', 'funcionarioId', 'bigint'],
    ['funcionario_nome', 'funcionarioNome', 'text'],
    ['etapa_id', 'etapaId', 'bigint'],
    ['etapa_nome', 'etapaNome', 'text'],
    ['hora_inicio', 'horaInicio', 'text'],
    ['hora_fim', 'horaFim', 'text'],
    ['total_horas', 'totalHoras', 'text'],
    ['descricao_servico', 'descricaoServico', 'text'],
    ['data', 'data', 'timestamptz'],
    ['data_atualizacao', 'dataAtualizacao', 'timestamptz'],
  ] },
  { table: 'm8_equipamentos', collection: 'equipamentoProduto', fields: [
    ['equipamento_id', 'equipamentoId', 'bigint'],
    ['equipamento_produto_id', 'equipamentoProdutoId', 'bigint'],
    ['numero_serie', 'numeroSerie', 'text'],
    ['horimetro', 'horimetro', 'enum_text'],
    ['horimetro_dois', 'horimetroDois', 'enum_text'],
    ['horimetro_tres', 'horimetroTres', 'enum_text'],
    ['box', 'box', 'text'],
    ['data_instalacao', 'dataInstalacao', 'timestamptz'],
    ['dias_garantia', 'diasGarantia', 'bigint'],
    ['marca_id', 'marcaId', 'bigint'],
    ['marca', 'marca', 'text'],
    ['equipamento_modelo', 'equipamentoModelo', 'text'],
    ['documento_origem', 'documentoOrigem', 'text'],
    ['defeitos', 'defeitos', 'text'],
    ['problema', 'problema', 'text'],
    ['solucao', 'solucao', 'text'],
    ['pendencia', 'pendencia', 'text'],
    ['observacoes', 'observacoes', 'text'],
    ['observacoes_internas', 'observacoesInternas', 'text'],
    ['data_atualizacao', 'dataAtualizacao', 'timestamptz'],
  ] },
  { table: 'm8_checklist_respostas', collection: 'checklistRespostas', fields: [
    ['checklist_pergunta_execucao_relacionada_id', 'checklistPerguntaExecucaoRelacionadaId', 'bigint'],
    ['metodo', 'metodo', 'text'],
    ['pergunta', 'pergunta', 'text'],
    ['avaliacao_nota', 'avaliacaoNota', 'numeric'],
    ['observacao', 'observacao', 'text'],
  ] },
  { table: 'm8_anexos', collection: 'anexos', fields: [
    ['descricao', 'descricao', 'text'],
  ] },
] as const satisfies readonly EntitySchema[];

export const maintenanceSchema: EntitySchema = {
  table: 'm8_os_manutencoes', collection: 'manutencoes', fields: [
    ['veiculo_pessoa_id','veiculoPessoaId','bigint'], ['veiculo_pessoa_nome','veiculoPessoaNome','text'],
    ['km_atual','kmAtual','bigint'], ['box','box','text'],
    ['data_ultima_troca_oleo','dataUltimaTrocaOleo','timestamptz'], ['km_ultima_troca','kmUltimaTroca','bigint'],
    ['km_rodado','kmRodado','bigint'], ['data_proxima_troca_oleo','dataProximaTrocaOleo','timestamptz'],
    ['aviso_antecedencia_troca_oleo','avisoAntecedenciaTrocaOleo','enum_text'], ['observacoes_troca_oleo','observacoesTrocaOleo','text'],
    ['quantidade_combustivel','quantidadeCombustivel','enum_text'], ['condicao_entrada','condicaoEntrada','enum_text'],
    ['data_proxima_revisao','dataProximaRevisao','timestamptz'], ['aviso_antecedencia','avisoAntecedencia','enum_text'],
    ['observacoes_revisao','observacoesRevisao','text'], ['observacao','observacao','text'],
    ['avarias','avarias','text'], ['defeitos','defeitos','text'], ['laudo','laudo','text'],
  ],
};
