// Contrato provisório baseado no briefing. Campos adicionais permanecem no payload JSONB.
export type M8Id = number | string;
export type M8Decimal = number | string;
export type M8Manutencao = Record<string, unknown>;
export interface M8OrdemServicoCompleta extends Record<string, unknown> {
  id: M8Id;
  clienteId?: M8Id | null;
  clienteNome?: string | null;
  clienteRazaoSocial?: string | null;
  clienteCpfCnpj?: string | null;
  dataAbertura?: string | null;
  dataEntregaPrevista?: string | null;
  dataEntrega?: string | null;
  emissao?: string | null;
  dataLancamento?: string | null;
  dataFaturamento?: string | null;
  dataAtualizacao?: string | null;
  dataGarantia?: string | null;
  tipoId?: M8Id | null;
  tipoNome?: string | null;
  contato?: string | null;
  funcionarioId?: M8Id | null;
  funcionarioNome?: string | null;
  revendaContratoId?: M8Id | null;
  revendaContratoNome?: string | null;
  enderecoEntregaId?: M8Id | null;
  enderecoEntregaNome?: string | null;
  condicaoPagamentoId?: M8Id | null;
  condicaoPagamentoNome?: string | null;
  responsavelTecnicoId?: M8Id | null;
  responsavelTecnicoNome?: string | null;
  numeroSequencia?: M8Id | null;
  situacaoId?: M8Id | null;
  situacaoNome?: string | null;
  statusLancamentoId?: M8Id | null;
  statusLancamentoNome?: string | null;
  status?: string | null;
  statusAprovacao?: M8Id | null;
  tipoAtendimentoId?: M8Id | null;
  tipoAtendimentoNome?: string | null;
  modalidadeAtendimentoId?: M8Id | null;
  modalidadeAtendimentoNome?: string | null;
  defeitosApontados?: string | null;
  modeloVeiculo?: string | null;
  placaVeiculo?: string | null;
  serie?: string | null;
  numeroSerie?: string | null;
  equipamento?: string | null;
  produtoEquipamentoId?: M8Id | null;
  modeloEquipamento?: string | null;
  documentoEquipamento?: string | null;
  tipoDocumentoFiscal?: M8Id | null;
  documentoFiscalId?: M8Id | null;
  documentoCompraId?: M8Id | null;
  documentoCompraDoc?: M8Id | null;
  imposto?: string | null;
  origemDados?: string | null;
  projetoId?: M8Id | null;
  projetoNome?: string | null;
  empresaId?: M8Id | null;
  empresaNome?: string | null;
  empresaGrupoNome?: string | null;
  totalGeral?: M8Decimal | null;
  ativo?: boolean | null;
  atualizadoPeloUsuarioId?: M8Id | null;
  observacao?: string | null;
  produtos?: M8ProdutoOS[] | null;
  servicos?: M8ServicoOS[] | null;
  apontamentos?: M8Apontamento[] | null;
  equipamentoProduto?: M8EquipamentoProduto | null;
  checklistRespostas?: M8ChecklistResposta[] | null;
  anexos?: M8Anexo[] | null;
  manutencao?: M8Manutencao | null;
}
export interface M8ProdutoOS extends Record<string, unknown> {
  id: M8Id;
  produtoId?: M8Id | null;
  produtoNome?: string | null;
  tipoContrato?: M8Id | null;
  referenciaFabricante?: string | null;
  multiploVenda?: M8Decimal | null;
  codigoSimilaridade?: string | null;
  descricaoDetalhadaNfe?: string | null;
  destinoEstoqueId?: M8Id | null;
  destinoEstoqueNome?: string | null;
  unidadeId?: M8Id | null;
  unidadeNome?: string | null;
  valorTotal?: M8Decimal | null;
  situacaoItemId?: M8Id | null;
  situacaoItemNome?: string | null;
  quantidade?: M8Decimal | null;
  valorUnitario?: M8Decimal | null;
  pesoLiquido?: M8Decimal | null;
  volumeNome?: string | null;
  observacaoInterna?: string | null;
  observacao?: string | null;
  saldo?: M8Decimal | null;
  faturado?: M8Decimal | null;
  operacaoFiscalId?: M8Id | null;
  tributacaoOperacaoFiscalId?: M8Id | null;
  cst?: string | null;
  quantidadeConversao?: M8Decimal | null;
  valorUnitarioConversao?: M8Decimal | null;
  valorUnitarioDesconto?: M8Decimal | null;
  percentualDesconto?: M8Decimal | null;
  valorDesconto?: M8Decimal | null;
  valorDescontoRateio?: M8Decimal | null;
  fatorConversao?: M8Decimal | null;
  valorTotalConversao?: M8Decimal | null;
  unidadeConversaoId?: M8Id | null;
  unidadeConversaoNome?: string | null;
  baseCalculoIcmsDiferencial?: M8Decimal | null;
  aliquotaIcms?: M8Decimal | null;
  aliquotaIcmsSt?: M8Decimal | null;
  percentualReducaoIcms?: M8Decimal | null;
  aliquotaMva?: M8Decimal | null;
  aliquotaPis?: M8Decimal | null;
  aliquotaCofins?: M8Decimal | null;
  aliquotaIpi?: M8Decimal | null;
  aliquotaFunrural?: M8Decimal | null;
  aliquotaIcmsDiferencial?: M8Decimal | null;
  valorIcms?: M8Decimal | null;
  valorIcmsSt?: M8Decimal | null;
  valorPis?: M8Decimal | null;
  valorCofins?: M8Decimal | null;
  valorIpi?: M8Decimal | null;
  valorIcmsDiferencial?: M8Decimal | null;
  aprovado?: string | null;
  codigoPedido?: string | null;
  numeroItemPedido?: M8Id | null;
  prazoEntrega?: string | null;
  percentualComissaoTabelaPreco?: M8Decimal | null;
  dataAtualizacao?: string | null;
  estaExcluido?: boolean | null;
}
export interface M8ServicoOS extends Record<string, unknown> {
  id: M8Id;
  servicoId?: M8Id | null;
  servicoNome?: string | null;
  quantidade?: M8Decimal | null;
  valorUnitario?: M8Decimal | null;
  valorTotal?: M8Decimal | null;
  dataAtualizacao?: string | null;
}
export interface M8Apontamento extends Record<string, unknown> {
  id: M8Id;
  servicoId?: M8Id | null;
  servicoNome?: string | null;
  funcionarioId?: M8Id | null;
  funcionarioNome?: string | null;
  etapaId?: M8Id | null;
  etapaNome?: string | null;
  horaInicio?: string | null;
  horaFim?: string | null;
  totalHoras?: string | null;
  descricaoServico?: string | null;
  data?: string | null;
  dataAtualizacao?: string | null;
}
export interface M8EquipamentoProduto extends Record<string, unknown> {
  id: M8Id;
  equipamentoId?: M8Id | null;
  equipamentoProdutoId?: M8Id | null;
  numeroSerie?: string | null;
  horimetro?: M8Decimal | null;
  horimetroDois?: M8Decimal | null;
  horimetroTres?: M8Decimal | null;
  box?: string | null;
  dataInstalacao?: string | null;
  diasGarantia?: M8Id | null;
  marcaId?: M8Id | null;
  marca?: string | null;
  equipamentoModelo?: string | null;
  documentoOrigem?: string | null;
  defeitos?: string | null;
  problema?: string | null;
  solucao?: string | null;
  pendencia?: string | null;
  observacoes?: string | null;
  observacoesInternas?: string | null;
  dataAtualizacao?: string | null;
}
export interface M8ChecklistResposta extends Record<string, unknown> {
  id: M8Id;
  checklistPerguntaExecucaoRelacionadaId?: M8Id | null;
  metodo?: string | null;
  pergunta?: string | null;
  avaliacaoNota?: M8Decimal | null;
  observacao?: string | null;
}
export interface M8Anexo extends Record<string, unknown> {
  id: M8Id;
  descricao?: string | null;
}
export interface M8ApiResponse<T> { data: T[]; errors?: unknown[] | null }
